# Generated by Django 3.2.8 on 2021-10-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211018_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watermark_avatar',
            new_name='watemark_avatar',
        ),
    ]
